//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowPlow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowPlow.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown through windscreen: {0}.
        /// </summary>
        internal static string ExceptionThrownMsg {
            get {
                return ResourceManager.GetString("ExceptionThrownMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished looking for snow.
        /// </summary>
        internal static string FinishedLooking {
            get {
                return ResourceManager.GetString("FinishedLooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for snow in {0} places.
        /// </summary>
        internal static string LookingForSnowN {
            get {
                return ResourceManager.GetString("LookingForSnowN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking in {0}.
        /// </summary>
        internal static string LookingInX {
            get {
                return ResourceManager.GetString("LookingInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plowing in {0}.
        /// </summary>
        internal static string PlowingInX {
            get {
                return ResourceManager.GetString("PlowingInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Describe.
        /// </summary>
        internal static string RootDescribe {
            get {
                return ResourceManager.GetString("RootDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping source {0}, disabled in plow definition.
        /// </summary>
        internal static string SkipXDisabled {
            get {
                return ResourceManager.GetString("SkipXDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping source {0}, not listed in a plow definition.
        /// </summary>
        internal static string SkipXNotListed {
            get {
                return ResourceManager.GetString("SkipXNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnowPlow: .
        /// </summary>
        internal static string SnowPlow_ {
            get {
                return ResourceManager.GetString("SnowPlow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ran out of time plowing tests in {0}, test process has been killed..
        /// </summary>
        internal static string TimoutInX {
            get {
                return ResourceManager.GetString("TimoutInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownDescribe {
            get {
                return ResourceManager.GetString("UnknownDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asked to plow unknown file {0}.
        /// </summary>
        internal static string UnknownFileX {
            get {
                return ResourceManager.GetString("UnknownFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broke plow, {0} returned exit code {1}.
        /// </summary>
        internal static string XReturnedErrorCodeY {
            get {
                return ResourceManager.GetString("XReturnedErrorCodeY", resourceCulture);
            }
        }
    }
}
